%YAML 1.1
---
mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: :9090
proxy-groups:
- name: ✈️ ‍起飞
  type: select
  proxies:
  - ⚡ ‍低延迟
  - 🇭🇰 ‍香港
  - 🇹🇼 ‍台湾
  - 🇨🇳 ‍中国
  - 🇸🇬 ‍新加坡
  - 🇯🇵 ‍日本
  - 🇺🇸 ‍美国
  - 🎏 ‍其他
  - 👆🏻 ‍指定
  - 👆🏻🇭🇰 ‍香港
  - 👆🏻🇹🇼 ‍台湾
  - 👆🏻🇨🇳 ‍中国
  - 👆🏻🇸🇬 ‍新加坡
  - 👆🏻🇯🇵 ‍日本
  - 👆🏻🇺🇸 ‍美国
  - 👆🏻🎏 ‍其他
  - DIRECT
- name: ⚡ ‍低延迟
  type: url-test
  tolerance: 50
  use:
  - All
- name: 🛩️ ‍墙内
  type: select
  proxies:
  - DIRECT
  - REJECT
  - ✈️ ‍起飞
- name: 💩 ‍广告
  type: select
  proxies:
  - REJECT
  - 🛩️ ‍墙内
  - ✈️ ‍起飞
- name: 📺 ‍B站
  type: select
  proxies:
  - 🇨🇳 ‍中国
  - 🇭🇰 ‍香港
  - 🇹🇼 ‍台湾
  - 🛩️ ‍墙内
  - ✈️ ‍起飞
  - 👆🏻🇭🇰 ‍香港
  - 👆🏻🇹🇼 ‍台湾
  - 👆🏻🇨🇳 ‍中国
- name: 🤖 ‍OpenAI
  type: select
  proxies:
  - 🛩️ ‍墙内
  - 👆🏻🎏 ‍其他
  - 👆🏻🇹🇼 ‍台湾
  - 👆🏻🇸🇬 ‍新加坡
  - 👆🏻🇯🇵 ‍日本
  - 👆🏻🇺🇸 ‍美国
  - 🇹🇼 ‍台湾
  - 🇸🇬 ‍新加坡
  - 🇯🇵 ‍日本
  - 🇺🇸 ‍美国
  - 🎏 ‍其他
  - ✈️ ‍起飞
- name: 🌐 ‍未知站点
  type: select
  proxies:
  - ✈️ ‍起飞
  - 🛩️ ‍墙内
  - 💩 ‍广告
- name: 🇭🇰 ‍香港
  type: url-test
  tolerance: 50
  use:
  - HK
- name: 🇹🇼 ‍台湾
  type: url-test
  tolerance: 50
  use:
  - TW
- name: 🇨🇳 ‍中国
  type: url-test
  tolerance: 50
  use:
  - CN
- name: 🇸🇬 ‍新加坡
  type: url-test
  tolerance: 50
  use:
  - SG
- name: 🇯🇵 ‍日本
  type: url-test
  tolerance: 50
  use:
  - JP
- name: 🇺🇸 ‍美国
  type: url-test
  tolerance: 50
  use:
  - US
- name: 🎏 ‍其他
  type: url-test
  tolerance: 50
  use:
  - Other
- name: 👆🏻 ‍指定
  type: select
  use:
  - All
- name: 👆🏻🇭🇰 ‍香港
  type: select
  use:
  - HK
- name: 👆🏻🇹🇼 ‍台湾
  type: select
  use:
  - TW
- name: 👆🏻🇨🇳 ‍中国
  type: select
  use:
  - CN
- name: 👆🏻🇸🇬 ‍新加坡
  type: select
  use:
  - SG
- name: 👆🏻🇯🇵 ‍日本
  type: select
  use:
  - JP
- name: 👆🏻🇺🇸 ‍美国
  type: select
  use:
  - US
- name: 👆🏻🎏 ‍其他
  type: select
  use:
  - Other
proxy-providers:
  All:
    type: http
    url:
    interval: 180
    path:
    health-check:
      enable: true
      url: https://i.ytimg.com/generate_204
      interval: 30
  HK:
  TW:
  CN:
  SG:
  JP:
  US:
  Other:
